name: Publish Node.js Package to npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - run: npm i

      # Build project and copy necessary files to dist
      - run: npm run build

      # Publish only the `dist` folder
      - run: npm publish --provenance --access public
        working-directory: dist  # Specify the working directory as `dist`
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}